title: An out of this planet blog!
author: Cosmin Cucu
email: cosmincucu@yahoo.com
description: > # this means to ignore newlines until "baseurl:"
  Hey there! This is my tech blog. I will express here my opinions on news
  and the latest technologies i am using, along with some guides.

twitter_username: cosmin_cucu
github_username:  cosmincucu

# Minima date format
# refer to http://shopify.github.io/liquid/filters/date/ if you want to customize this
minima:
  date_format: "%a, %b %d, %y"

# If you want to link only specific pages in your header, uncomment
# this and add the path to the pages in order as they should show up
#header_pages:
# - about.html

disqus:
    shortname: cosmin_cucu

# Build settings
markdown: kramdown
theme: jekyll-theme-minimal
exclude:
  - Gemfile
  - Gemfile.lock
